### ISSUE TITLE
Strange syntax error here

### ISSUE THREAD

**Issue by mindvox** [hubot-archive/hubot-nationalrail#2]
Whenever I issue a command such as `trains to <station>` this error is thrown and hubot doesn't reply. Any ideas?

```
[Wed May 13 2015 04:17:06 GMT+0000 (UTC)] ERROR SyntaxError: Unexpected token <
at Object.parse (native)
at /home/netfox/jarvis/node_modules/hubot-nationalrail/src/nationalrail.coffee:48:7, <js>:37:21
at IncomingMessage.<anonymous> (/home/netfox/jarvis/node_modules/hubot/node_modules/scoped-http-client/src/index.js:83:20)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16
at process._tickCallback (node.js:355:11)
```

Regards,
Karl

**Comment by sapg** [comment]
I have the same problem but only started happening recently so I suspect it is something to do with a dependency that may have been updated.

**Comment by johnhamelink** [comment]
It's probably because national rails' API changed. Feel free to submit a PR to fix this :)

**Comment by jackolney** [comment]
Anyone managed to get their head around calls to the new National Rail API? [datafeeds.nationrail.co.uk](datafeeds.nationrail.co.uk)
